#!/usr/bin/env python3
"""
Keyword Spotting System - FPGA-Compatible Model Training Script
Author: Tony Korycki
Date: October 25, 2025

Trains a compact MLP on FFT magnitude features (generated by make_features.py)
for real-time keyword detection on FPGA (e.g., Basys-3).
"""

import os
import argparse
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import tensorflow as tf
from keras import layers, models, regularizers
from keras.callbacks import EarlyStopping
from utils.plotting import plot_history, plot_confusion_rect


# ----------------------------
# Argument parser
# ----------------------------
def parse_args():
    parser = argparse.ArgumentParser(description="Train FPGA-compatible KWS model")
    parser.add_argument("--features_dir", type=str, default="data/processed",
                        help="Directory containing features.npy and labels.npy")
    parser.add_argument("--output_dir", type=str, default="models",
                        help="Where to save trained model and plots")
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--batch_size", type=int, default=32)
    parser.add_argument("--hidden_size", type=int, default=32)
    parser.add_argument("--l2", type=float, default=0.001)
    parser.add_argument("--dropout", type=float, default=0.2)
    parser.add_argument("--early_stopping", action="store_true")
    return parser.parse_args()


# ----------------------------
# Utility helpers
# ----------------------------
def ensure_dir(path):
    if not os.path.exists(path):
        os.makedirs(path)


# ----------------------------
# Model builder
# ----------------------------
def build_model(input_shape, num_classes, hidden_size=32, l2_reg=0.001, dropout_rate=0.2):
    """Tiny MLP suitable for FPGA inference with regularization to prevent overfitting."""
    model = models.Sequential([
        layers.Input(shape=input_shape),
        layers.Dense(hidden_size, activation="relu",
                     kernel_regularizer=regularizers.l2(l2_reg)),
        layers.Dropout(dropout_rate),
        layers.Dense(hidden_size // 2, activation="relu",
                     kernel_regularizer=regularizers.l2(l2_reg)),
        layers.Dropout(dropout_rate),
        layers.Dense(num_classes, activation="softmax")
    ])
    model.compile(optimizer="adam",
                  loss="sparse_categorical_crossentropy",
                  metrics=["accuracy"])
    return model


# ----------------------------
# Main
# ----------------------------
def main():
    args = parse_args()
    ensure_dir(args.output_dir)

    # 1. Load data
    X = np.load(os.path.join(args.features_dir, "features.npy"))
    y = np.load(os.path.join(args.features_dir, "labels.npy"))

    labels_actual_path = os.path.join(args.features_dir, "labels_actual.npy")
    label_types_path = os.path.join(args.features_dir, "label_types.npy")
    filenames_path = os.path.join(args.features_dir, "filenames.npy")
    if os.path.exists(filenames_path):
        filenames = np.load(filenames_path)
    else:
        filenames = np.array([f"sample_{i}.wav" for i in range(len(y))])
    if os.path.exists(labels_actual_path) and os.path.exists(label_types_path):
        y_actual = np.load(labels_actual_path)
        label_types = np.load(label_types_path)
    else:
        y_actual = y.copy()
        label_types = np.array([f"class {i}" for i in range(len(np.unique(y)))])

    print(f"Loaded features: {X.shape}, labels: {y.shape}")
    X = X / np.max(X)
    num_classes = len(np.unique(y))
    label_names = [f"class {i}" for i in range(num_classes)]

    # 2. Split
    X_train, X_test, y_train, y_test, filenames_train, filenames_test = train_test_split(
        X, y, filenames, test_size=0.2, stratify=y, random_state=42)

    _, y_actual_test = train_test_split(
        y_actual, test_size=0.2, stratify=y, random_state=42
    )

    # 3. Build and train
    model = build_model(X_train.shape[1:], num_classes,
                        hidden_size=args.hidden_size,
                        l2_reg=args.l2, dropout_rate=args.dropout)
    model.summary()

    callbacks = []
    if args.early_stopping:
        callbacks.append(EarlyStopping(monitor="val_loss", patience=5,
                                       restore_best_weights=True, verbose=1))

    history = model.fit(X_train, y_train,
                        validation_split=0.2,
                        epochs=args.epochs,
                        batch_size=args.batch_size,
                        callbacks=callbacks,
                        verbose="1")

    # 4. Evaluate
    test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
    print(f"\nTest Accuracy: {test_acc:.4f}")

    y_pred = np.argmax(model.predict(X_test), axis=-1)
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))
    plot_history(history)
    plot_confusion_rect(y_actual_test, y_pred, label_types, label_names)

    # 5. Misclassified samples
    misclassified_idx = np.where(y_pred != y_test)[0]
    print(f"\nMisclassified: {len(misclassified_idx)} / {len(y_test)}")
    if len(misclassified_idx) > 0:
        print("First 10 misclassifications:")
        for i in misclassified_idx[:10]:
            print(f"  {filenames_test[i]} -> true: {y_test[i]}, pred: {y_pred[i]}")

    with open(os.path.join(args.output_dir, "misclassified.txt"), "w") as f:
        for i in misclassified_idx:
            f.write(f"{filenames_test[i]}\ttrue:{y_test[i]}\tpred:{y_pred[i]}\n")

    # 6. Save model
    model_file = os.path.join(args.output_dir, "kws_model.h5")
    model.save(model_file)
    print(f"\nModel saved to {model_file}")
    
    # 7. Create golden test vectors for FPGA validation
    # Save a subset of test data with float model predictions
    num_test_vectors = min(100, len(X_test))
    test_input = X_test[:num_test_vectors]
    test_output = y_pred[:num_test_vectors]  # Float model predictions (not ground truth)
    
    np.save(os.path.join(args.output_dir, "test_input.npy"), test_input)
    np.save(os.path.join(args.output_dir, "test_output.npy"), test_output)
    print(f"Saved {num_test_vectors} golden test vectors (float model predictions)")


if __name__ == "__main__":
    main()
