#!/usr/bin/env python3
"""
Keyword Spotting System - FPGA-Compatible Model Training Script
Author: Tony Korycki
Date: October 18, 2025

Trains a compact MLP on FFT magnitude features (generated by make_features.py)
for real-time keyword detection on FPGA (e.g., Basys-3).
"""

import os
import argparse
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
import tensorflow as tf
import keras
from keras import layers, models, regularizers
from keras.callbacks import EarlyStopping

# ----------------------------
# Argument parser
# ----------------------------
def parse_args():
    parser = argparse.ArgumentParser(description="Train FPGA-compatible KWS model")
    parser.add_argument("--features_dir", type=str, default="data/processed",
                        help="Directory containing features.npy and labels.npy")
    parser.add_argument("--output_dir", type=str, default="models",
                        help="Where to save trained model and plots")
    parser.add_argument("--epochs", type=int, default=40)
    parser.add_argument("--batch_size", type=int, default=32)
    parser.add_argument("--hidden_size", type=int, default=32,
                        help="Hidden layer size (keep small for FPGA feasibility)")
    parser.add_argument("--quantize", action="store_true",
                        help="Export an 8-bit quantized model for hardware")
    parser.add_argument("--l2", type=float, default=0.001,
                        help="L2 regularization strength")
    parser.add_argument("--dropout", type=float, default=0.2,
                        help="Dropout rate (0 to disable)")
    parser.add_argument("--early_stopping", action="store_true",
                        help="Enable early stopping based on validation loss")
    return parser.parse_args()


# ----------------------------
# Utility helpers
# ----------------------------
def ensure_dir(path):
    if not os.path.exists(path):
        os.makedirs(path)


def plot_history(history):
    plt.figure(figsize=(12, 4))
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label="Train")
    plt.plot(history.history['val_accuracy'], label="Val")
    plt.title("Accuracy")
    plt.legend()
    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label="Train")
    plt.plot(history.history['val_loss'], label="Val")
    plt.title("Loss")
    plt.legend()
    plt.tight_layout()
    plt.show()


def plot_confusion(y_true, y_pred, label_names):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(6, 5))
    plt.imshow(cm, interpolation='nearest', cmap='Blues')
    plt.title("Confusion Matrix")
    plt.colorbar()
    ticks = np.arange(len(label_names))
    plt.xticks(ticks, label_names, rotation=45)
    plt.yticks(ticks, label_names)
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            plt.text(j, i, str(cm[i, j]), ha='center', va='center',
                     color='white' if cm[i, j] > cm.max()/2 else 'black')
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.tight_layout()
    plt.show()


def plot_confusion_rect(y_true_actual, y_pred, true_label_names, pred_label_names):
    """
    Rectangular confusion matrix:
    rows = actual input types (folder-based), cols = model predicted classes.
    """
    n_true = len(true_label_names)
    n_pred = len(pred_label_names)
    cm = np.zeros((n_true, n_pred), dtype=np.int32)
    for t, p in zip(y_true_actual, y_pred):
        cm[t, p] += 1

    plt.figure(figsize=(7, 5))
    plt.imshow(cm, interpolation='nearest', cmap='Blues', aspect='auto')
    plt.title("Confusion Matrix (Actual types vs Predicted classes)")
    plt.colorbar()
    plt.yticks(np.arange(n_true), true_label_names)
    plt.xticks(np.arange(n_pred), pred_label_names, rotation=45)
    thresh = cm.max() / 2 if cm.max() > 0 else 0.5
    for i in range(n_true):
        for j in range(n_pred):
            plt.text(j, i, str(cm[i, j]), ha='center', va='center',
                     color='white' if cm[i, j] > thresh else 'black')
    plt.xlabel("Predicted")
    plt.ylabel("Actual (input types)")
    plt.tight_layout()
    plt.show()


# ----------------------------
# Model builder
# ----------------------------
def build_model(input_shape, num_classes, hidden_size=32, l2_reg=0.001, dropout_rate=0.2):
    """Tiny MLP suitable for FPGA inference with regularization to prevent overfitting."""
    model = models.Sequential([
        layers.Input(shape=input_shape),
        layers.Dense(hidden_size, activation='relu',
                    kernel_regularizer=regularizers.l2(l2_reg)),
        layers.Dropout(dropout_rate),
        layers.Dense(hidden_size // 2, activation='relu',
                    kernel_regularizer=regularizers.l2(l2_reg)),
        layers.Dropout(dropout_rate),
        layers.Dense(num_classes, activation='softmax')
    ])
    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model


# ----------------------------
# Main
# ----------------------------
def main():
    args = parse_args()
    ensure_dir(args.output_dir)

    # 1️⃣ Load data
    X = np.load(os.path.join(args.features_dir, "features.npy"))
    y = np.load(os.path.join(args.features_dir, "labels.npy"))
    
    # Load additional label data if available
    labels_actual_path = os.path.join(args.features_dir, "labels_actual.npy")
    label_types_path = os.path.join(args.features_dir, "label_types.npy")
    if os.path.exists(labels_actual_path) and os.path.exists(label_types_path):
        y_actual = np.load(labels_actual_path)
        label_types = np.load(label_types_path)
        print(f"Loaded actual labels from folders: {label_types}")
    else:
        print("⚠️ No actual labels found. Using binary labels for visualization.")
        y_actual = y.copy()
        label_types = np.array([f"class {i}" for i in range(len(np.unique(y)))])
    
    print(f"Loaded features {X.shape}, labels {y.shape}")

    # 2️⃣ Basic normalization (optional, helps training)
    X = X / np.max(X)

    num_classes = len(np.unique(y))
    label_names = [f"class {i}" for i in range(num_classes)]

    print(f"Detected {num_classes} classes → {label_names}")

    # 3️⃣ Split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=42
    )
    
    # Split actual labels to align with test set
    _, y_actual_test = train_test_split(
        y_actual, test_size=0.2, stratify=y, random_state=42
    )

    # 4️⃣ Build and train
    model = build_model(
        X_train.shape[1:], 
        num_classes, 
        hidden_size=args.hidden_size,
        l2_reg=args.l2,
        dropout_rate=args.dropout
    )
    model.summary()
    
    # Callbacks for training
    callbacks = []
    if args.early_stopping:
        callbacks.append(
            EarlyStopping(
                monitor='val_loss',
                patience=5,
                restore_best_weights=True,
                verbose=1
            )
        )

    history = model.fit(
        X_train, y_train,
        validation_split=0.2,
        epochs=args.epochs,
        batch_size=args.batch_size,
        callbacks=callbacks,
        verbose="1"
    )

    # 5️⃣ Evaluate
    test_loss, test_acc = model.evaluate(X_test, y_test, verbose="0")
    print(f"\n✅ Test Accuracy: {test_acc:.4f}")

    y_pred = np.argmax(model.predict(X_test), axis=-1)
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    # 6️⃣ Visualizations
    plot_history(history)
    # Standard confusion matrix
    #plot_confusion(y_test, y_pred, label_names)
    # Rectangular confusion matrix using actual labels from folders
    plot_confusion_rect(y_actual_test, y_pred, label_types, label_names)

    # 7️⃣ Save model
    model_file = os.path.join(args.output_dir, "kws_model.h5")
    model.save(model_file)
    print(f"Model saved to {model_file}")

    # 8️⃣ Optional quantization (post-training)
    if args.quantize:
        converter = tf.lite.TFLiteConverter.from_keras_model(model)
        converter.optimizations = {tf.lite.Optimize.DEFAULT}
        tflite_model = converter.convert()
        q_file = os.path.join(args.output_dir, "kws_model_quantized.tflite")
        with open(q_file, "wb") as f:
            f.write(bytes(tflite_model))
        print(f"Quantized model saved to {q_file}")


if __name__ == "__main__":
    main()
